import mongoose from "mongoose";
const vehicleSchema=mongoose.Schema({
    hubId:{
        type:String,
    },
    vehicleName:{
        type:String,
        require:true
    },
    brand:{
        type:String,
        require:true
    },
    year:{
        type:Number,
        require:true
    },
    class:{
        type:String
    },
    bodyType:{
        type:String,
        require:true
    },
    transmission:{
        type:String,
        require:true
    },
    fuelType:{
        type:String,
        require:true
    },
    noOfSeat:{
        type:Number,
        require:true
    },
    images:{
        type:Array,
        require:true
    },
    review:{
        type:String,
        require:true
    },
    list:{
        type:Boolean,
        default:true
    }
})
const vehicleModel=mongoose.model('vehicle',vehicleSchema)
export default vehicleModel